run_name: "imagenet-resnet50"

checkpoint: "models/model.ckpt"

accelerator: 'gpu'
strategy: null
devices: 1
num_nodes: null

logger: null

precision: 16
use_bf16_if_ampere: false

seed: 123
matmul_precision: "medium"

datamodule: "imagenet"
data_params:
  num_workers: 8
  batch_size: 128

model: "imagenet-resnet50"
