[ssh]
user = "s204071"
host = "login.hpc.dtu.dk"
default_cwd = "/work3/s204071/"

[github]
access_token = "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"

[project]
name = "bsc"
path = "/work3/s204071/bsc"
default_deploy_branch = "master"