queue = "gpua100"
name = "train-imagenet-vit-mem-score"
walltime = { hours = 72, minutes = 0 }
cpu = 16
single_host = true
memory = 30
standard_output = { name = "logs/train-imagenet-vit-mem-score.out", overwrite = true }
error_output = { name = "logs/train-imagenet-vit-mem-score.err", overwrite = true }
use_gpu = { num_of_gpus = 1 }

commands = [
    "module load python3/3.10.7",
    "module load cuda/11.7",
    "source venv/bin/activate",
    """python3 src/models/train_model.py \
       trainer=hpc-vit \
       model=imagenet-vit \
       dataset=imagenet-mem-score \
       name=imagenet-vit-mem-score \
       dataset.batch_size=512
    """
]
