queue = "gpua100"
name = "train-imagenet"
walltime = { hours = 30, minutes = 0 }
cpu = 32
single_host = true
memory = 30
standard_output = { name = "logs/train-imagenet-2x.out", overwrite = true }
error_output = { name = "logs/train-imagenet-2x.err", overwrite = true }
use_gpu = { num_of_gpus = 2 }

commands = [
    "module load python3/3.10.7",
    "module load cuda/11.7",
    "source venv/bin/activate",
    """python3 src/models/train_model.py trainer=hpc \
       dataset=imagenet-distributed \
       model=imagenet-resnet50 \
       model.sync_dist_val=true \
       name=imagenet-resnet-50-2x"""
]
