queue = "gpua100"
name = "train-imagenet-mem-score"
walltime = { hours = 30, minutes = 0 }
cpu = 16
single_host = true
memory = 8
standard_output = { name = "logs/train-imagenet-mem-score.out", overwrite = true }
error_output = { name = "logs/train-imagenet-mem-score.err", overwrite = true }
use_gpu = { num_of_gpus = 1 }

commands = [
    "module load python3/3.10.7",
    "module load cuda/11.7",
    "source venv/bin/activate",
    "python3 src/models/train_model.py trainer=hpc-1x-gpu dataset=imagenet-mem-score name=imagenet-resnet-50-mem-score"
]
