n_epochs: 100
limit_train_batches: null
accelerator: 'cpu'
strategy: "auto"
devices: 1
num_nodes: null
precision: "16-mixed"
use_bf16_if_ampere: false
matmul_precision: "medium"
log_loss_curves: true
log_model: "all"
logger: "wandb"
