run_name: "imagenet-resnet50"

n_epochs: 100
limit_train_batches: null

accelerator: 'gpu'
strategy: null
devices: 1
num_nodes: null

logger: null

precision: 16
use_bf16_if_ampere: false

seed: 123
matmul_precision: "medium"

datamodule: "imagenet"
data_params:
  num_workers: 8
  batch_size: 64

model: "imagenet-resnet50"
model_params:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  max_epochs: 100
