run_name: "imagenet-resnet50-multi-gpu-dev"

n_epochs: 5
limit_train_batches: 10
limit_val_batches: 10

accelerator: 'gpu'
strategy: 'ddp'
devices: 2
num_nodes: null

logger: "wandb"

precision: 16
use_bf16_if_ampere: false

seed: 123
matmul_precision: "medium"

log_every_n: 1
log_loss_curves: true
log_model: "all"

datamodule: "imagenet"
data_params:
  num_workers: 16
  batch_size: 128

model: "imagenet-resnet50"
model_params:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  max_epochs: 100
  sync_dist_train: false
  sync_dist_val: true
