run_name: "imagenet-resnet50-multi-gpu"

n_epochs: 100
limit_train_batches: null

accelerator: 'gpu'
strategy: 'ddp'
devices: 2
num_nodes: null

logger: "wandb"

precision: 16
use_bf16_if_ampere: true

seed: 123
matmul_precision: "medium"

datamodule: "imagenet"
data_params:
  num_workers: null
  batch_size: 128

model: "imagenet-resnet50"
model_params:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  max_epochs: 100
  sync_dist: true
