run_name: "imagenet-resnet50-profile"

n_epochs: 5
limit_train_batches: 25
limit_val_batches: 25

accelerator: 'gpu'
strategy: null
devices: 1
num_nodes: null

logger: null

profiler: "simple"
log_loss_curves: true
log_model: "all"

precision: 16
use_bf16_if_ampere: false

seed: 123
matmul_precision: "medium"

datamodule: "imagenet"
data_params:
  num_workers: 8
  batch_size: 128

model: "imagenet-resnet50"
model_params:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  max_epochs: 100
