queue = "hpc"
name = "convert-imagenet"
walltime = { hours = 12, minutes = 0 }
single_host = true
cpu = 16
memory = 4
standard_output =  { name = "logs/imagenet_wds.out", overwrite = true }
error_output =  { name = "logs/imagenet_wds.err", overwrite = true }

commands = [
    "module load python3/3.10.7",
    "source venv/bin/activate",
    """python3 src/data/convert_imagenet_to_wds.py \
       data/raw/imagenet/ILSVRC/Data/CLS-LOC/train \
       data/raw/imagenet \
       data/processed/imagenet_wds \
       --split val"""
]
