queue = "hpc"
name = "plots"
walltime = { hours = 1, minutes = 0 }
single_host = true
cpu = 8
memory = 48
standard_output =  { name = "logs/plots.out", overwrite = true }
error_output =  { name = "logs/plots.err", overwrite = true }

commands = [
    "module load python3/3.10.7",
    "source venv/bin/activate",
    "python src/visualization/visualize.py --name imagenet data/processed/imagenet/train_probe_suite_c_scores.pt models/losses/imagenet-resnet-50-c-score-20230413_1115/ reports/figures/"
]
