queue = "gpua100"
name = "train-model"
walltime = { hours = 16, minutes = 0 }
cpu = 16
single_host = true
memory = 8
standard_output = "logs/train-model.out"
error_output = "logs/train-model.err"
use_gpu = { num_of_gpus = 2 }

commands = [
    "source venv/bin/activate",
    "module load python3/3.10.7",
    "module load cuda/11.7",
    "python3 src/models/train_model.py training=hpc"
]
