queue = "gpua100"
name = "train-model"
walltime = { hours = 16, minutes = 0 }
cpu = 24
memory = 8
standard_output = { name = "logs/train-model.out", overwrite = true }
error_output = { name = "logs/train-model.err", overwrite = true }
use_gpu = { num_of_gpus = 2 }
core_p_tile_size = 8

commands = [
    "module load python3/3.10.7",
    "module load cuda/11.7",
    "source venv/bin/activate",
    "export CUDA_VISIBLE_DEVICES=0,1",
    "export MASTER_ADDR=$(HOSTNAME)",
    "cat $LSB_AFFINITY_HOSTFILE > hostfile.txt",
    "cat $LSB_DJOB_RANKFILE > rankfile.txt",
    "printenv >> env.txt"
]
