queue = "gpua100"
name = "train-imagenet"
walltime = { hours = 30, minutes = 0 }
cpu = 16
single_host = true
memory = 8
standard_output = { name = "logs/train-imagenet.out", overwrite = true }
error_output = { name = "logs/train-imagenet.err", overwrite = true }
use_gpu = { num_of_gpus = 2 }

commands = [
    "module load python3/3.10.7",
    "module load cuda/11.7",
    "source venv/bin/activate",
    "python3 src/models/train_model.py trainer=hpc dataset=imagenet dataset.batch_size=128 model=imagenet-resnet50 name=imagenet-resnet-50-2x"
]
