queue = "gpua100"
name = "train-model"
walltime = { hours = 16, minutes = 0 }
cpu = 24
memory = 8
standard_output = { name = "logs/train-model.out", overwrite = true }
error_output = { name = "logs/train-model.err", overwrite = true }
use_gpu = { num_of_gpus = 2 }
core_p_tile_size = 8

commands = [
    "module load python3/3.10.7",
    "module load cuda/11.7",
    "source venv/bin/activate",
    "printenv"
]
