queue = "gpua100"
name = "train-cifar10-vit"
walltime = { hours = 72, minutes = 0 }
cpu = 16
single_host = true
memory = 4
standard_output = { name = "logs/train-cifar10-vit.out", overwrite = true }
error_output = { name = "logs/train-cifar10-vit.err", overwrite = true }
use_gpu = { num_of_gpus = 1 }

commands = [
    "module load python3/3.10.7",
    "module load cuda/11.7",
    "source venv/bin/activate",
    "python3 src/models/train_model.py trainer=hpc-cifar dataset=cifar10 model=cifar10-vit name=cifar10-vit"
]
