queue = "gpua100"
name = "train-cifar100-1x-gpu"
walltime = { hours = 72, minutes = 0 }
cpu = 16
single_host = true
memory = 8
standard_output = { name = "logs/train-cifar100-1x-gpu.out", overwrite = true }
error_output = { name = "logs/train-cifar100-1x-gpu.err", overwrite = true }
use_gpu = { num_of_gpus = 1 }

commands = [
    "module load python3/3.10.7",
    "module load cuda/11.7",
    "source venv/bin/activate",
    "python3 src/models/train_model.py trainer=hpc-cifar-1x-gpu dataset=cifar100-1x-gpu model=cifar100-resnet50-1x-gpu"
]
