name: "Run isort"
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - name: Install Poetry
      run: |
        pipx install poetry
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install dependencies
      run: |
        poetry install
    - name: Sort imports with isort
      run: |
        poetry run isort src/